[Server]
address = "0.0.0.0"
port = 8080
https = false
httpMaxConnections = 100

[Cache]
listMinutes = 240
rssMinutes = 10
redisHost = "redis"
redisPort = 6379
redisPassword = ""
redisConnections = 20

[Config]
hmacKey = "change-this-in-production"
base64Media = false
enableRSS = true
enableDebug = false
proxy = ""
proxyAuth = ""
tokenCount = 10

